### ISSUE TITLE
Bug found! File operation has no way to cancel.

### ISSUE THREAD

**Issue by SSQ123** [eiiiiix/EixMode9#1]
**What version of EixMode9 are you using?**
1.4.4.8.1-E
**How are you launching it? (If applicable)**
Luma3DS
**What version is your SysNand on (Emu/RedNand if applicable), and is it Retail or Dev?**
Sys 11.6 retail
**Now, what exactly IS the issue?**
On some of the file operations A and B mean yes with no way to cancel.
**Explain in great detail all neccessary steps to reproduce.
I tried to boot a firm file and decided not to but when I clicked cancel it still booted!

Please don't ask stupid or GM9-related questions.

**Comment by eiiiiix** [comment]
ok ill look into that

**Comment by Moire9** [comment]
I don't have this problem when booting a firm.

**Comment by eiiiiix** [comment]
this isnt an issue
canceling works fine and theres no issues in the source
only explanation i can give is a hardware error of accidentally pressing the wrong button
