### ISSUE TITLE
Sample Issue

### ISSUE THREAD

**Issue by eiiiiix** [eiiiiix/EixMode9#1]
im too lazy to add a issue template so heres what you should include in your issues if you have any
1 what happened
2 how you did it
3 what version are you using
4 what system is it (retail or dev)
5 any other details

example:
Accidently locked my perms
i tryed to mount the FIRM0 partiton with the hex editor
1.4.3-E
retail unit
i was able to just reboot to fix it but its still a minor annoyance

please dont make issues about random crap like
"how do i do X"
"i accidently deleted X"
"i accidently overwrote X"
"you spelt X wrong"
"correct your grammers in X"
i will ignore these

**Comment by SirNapkin1334** [comment]
Hey, since you're ReadMe.md didn't tell me much, what exactly is different about this? Should I use it over standard GM9?

**Comment by SirNapkin1334** [comment]
I made an issue template for you. I would ass it (dammit) in a Pull Request but I don't know how to make a pull request.
[ISSUE_TEMPLATE.txt](https://github.com/eiiiiix/EixMode9/files/1439698/ISSUE_TEMPLATE.txt)
Just don't forget to change it to an MD.

**Comment by eiiiiix** [comment]
ok
i just noticed this XD
you told me about it on discord but me being my stupid self was unable to find it until i noticed this had comments on it
